### ISSUE TITLE
Hello! How to solve this problem？

### ISSUE THREAD

**Issue by SaltwaterLHL** [sniklaus/pytorch-spynet#10]
Traceback (most recent call last):
  File "/home/lhl/pytorch-spynet-master/run.py", line 131, in <module>
    moduleNetwork = Network().cuda().eval()
  File "/home/lhl/pytorch-spynet-master/run.py", line 100, in __init__
    self.load_state_dict(torch.load('./network-' + arguments_strModel + '.pytorch'))
  File "/home/public/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/public/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by sniklaus** [comment]
Looks like downloading the weights again might solve this problem: https://github.com/sniklaus/pytorch-sepconv/issues/26#issuecomment-441220029
