### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by xuleyoung** [sniklaus/pytorch-spynet#12]
Hi! I meet this problem when run run.py. 
my environment: CUDA 8 + cudnn 7.1+python 3.7. Thank you~
Details as following:
Traceback (most recent call last):
  File "/media/data2/xly/net_code/pytorch-liteflownet-master/run.py", line 377, in <module>
    tensorOutput = estimate(tensorFirst, tensorSecond)
  File "/media/data2/xly/net_code/pytorch-liteflownet-master/run.py", line 363, in estimate
    tensorFlow = torch.nn.functional.interpolate(input=moduleNetwork(tensorPreprocessedFirst, tensorPreprocessedSecond), size=(intHeight, intWidth), mode='bilinear', align_corners=False)
  File "/home/xly/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/data2/xly/net_code/pytorch-liteflownet-master/run.py", line 332, in forward
    tensorFlow = self.moduleSubpixel[intLevel](tensorFirst[intLevel], tensorSecond[intLevel], tensorFeaturesFirst[intLevel], tensorFeaturesSecond[intLevel], tensorFlow)
  File "/home/xly/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/data2/xly/net_code/pytorch-liteflownet-master/run.py", line 226, in forward
    tensorFeaturesSecond = Backward(tensorInput=tensorFeaturesSecond, tensorFlow=tensorFlow * self.dblBackward)
  File "/media/data2/xly/net_code/pytorch-liteflownet-master/run.py", line 61, in Backward
    return torch.nn.functional.grid_sample(input=tensorInput, grid=(Backward_tensorGrid[str(tensorFlow.size())] + tensorFlow).permute(0, 2, 3, 1), mode='bilinear', padding_mode='zeros')
  File "/home/xly/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2597, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by sniklaus** [comment]
Looks like an issue with PyTorch or cuDNN. What is the resolution of your images?

- https://github.com/pytorch/pytorch/issues/7258
- https://github.com/pytorch/pytorch/issues/16935
- https://github.com/pytorch/pytorch/issues/18561

I am afraid that I will not be able to address this issue for you though since it is not an issue with the code that I provide in this repository per se. If your images had a very large resolution then you might be able to get around this issue by downscaling them to 1080p or less. Otherwise you may have to update your environment, version `7.1` of cuDNN may be dated by now.

**Comment by xuleyoung** [comment]
Thx,  I would like know these magic numbers are written to the output file.
numpy.array([ 80, 73, 69, 72 ], numpy.uint8).tofile(objectOutput)
Thx

**Comment by sniklaus** [comment]
Please see `TAG_FLOAT` or `TAG_STRING` at: http://vision.middlebury.edu/flow/code/flow-code/flowIO.cpp
